# Generated by Django 3.0.8 on 2022-01-12 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='gramsFiber',
        ),
    ]
